version: '2'
services:
    blogsport-postgresql:
        container_name: blogsport-postgresql
        image: postgres:9.5.4
        # volumes:
        #     - ~/volumes/jhipster/blogsport/postgresql/:/var/lib/postgresql/
        environment:
            - POSTGRES_USER=blogsport
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
